# Generated by Django 2.2.2 on 2019-06-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='extras',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
