# Generated by Django 2.2.3 on 2019-07-02 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_onlineplayers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineplayers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
