# Generated by Django 2.2.3 on 2019-07-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20190702_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlinePlayers',
        ),
    ]
