
export const GET_ERRORS = "GET_ERRORS"
export const GET_MESSAGES = "GET_MESSAGES"
export const CREATE_MESSAGE = "CREATE_MESSAGE"

export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"


export const GET_GAMEPLAY = "GET_GAMEPLAY"
export const GET_WAR_GAMEPLAY = "GET_WAR_GAMEPLAY"
export const MAKE_NEW_GAME = "MAKE_NEW_GAME"
export const GET_WAR_ACTIVEGAMES = "GET_WAR_ACTIVEGAMES"
export const GET_NEWGAME = "GET_NEWGAME"
export const GET_ACTIVEGAMES = "GET_ACTIVEGAMES"
export const ANIMATION_STATUS = "ANIMATION_STATUS"
export const MEMORY_ANIMATION = "MEMORY_ANIMATION"
export const GET_ACTIVEPLAYERS = "GET_ACTIVEPLAYERS"
export const SET_GAME = "SET_GAME"