# Generated by Django 2.2.2 on 2019-07-01 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_extras'),
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turns',
            name='game_id',
        ),
        migrations.AlterField(
            model_name='turns',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memoryuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorygame', to='games.Games')),
            ],
        ),
        migrations.AddField(
            model_name='turns',
            name='round_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='memory.Rounds'),
        ),
    ]
