# Generated by Django 2.2.2 on 2019-07-02 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_auto_20190701_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memoryrounds', to='games.Games'),
        ),
        migrations.AlterField(
            model_name='turns',
            name='round_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='memory.Rounds'),
        ),
    ]
