# Generated by Django 2.2.2 on 2019-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='prizeCard',
            field=models.IntegerField(null=True),
        ),
    ]
