# Generated by Django 2.2.2 on 2019-06-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultgame', '0002_auto_20190622_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='noOfPlayers',
            new_name='no_of_players',
        ),
        migrations.RenameField(
            model_name='rounds',
            old_name='game_Id',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='turns',
            old_name='round_Id',
            new_name='round_id',
        ),
        migrations.RemoveField(
            model_name='players',
            name='game_Id',
        ),
        migrations.AddField(
            model_name='players',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='defaultgame.Games'),
        ),
    ]
