# Generated by Django 2.2.2 on 2019-06-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultgame', '0003_auto_20190622_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='defaultgame.Games'),
        ),
        migrations.RemoveField(
            model_name='players',
            name='player',
        ),
        migrations.AddField(
            model_name='players',
            name='player',
            field=models.ManyToManyField(to='defaultgame.Games'),
        ),
        migrations.AlterField(
            model_name='turns',
            name='action',
            field=models.IntegerField(null=True),
        ),
    ]
