# Generated by Django 2.2.2 on 2019-06-23 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defaultgame', '0004_auto_20190623_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='game_id',
        ),
        migrations.AddField(
            model_name='players',
            name='game_id',
            field=models.ManyToManyField(to='defaultgame.Games'),
        ),
        migrations.RemoveField(
            model_name='players',
            name='player',
        ),
        migrations.AddField(
            model_name='players',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
