# Generated by Django 2.2.2 on 2019-06-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultgame', '0005_auto_20190623_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='game_id',
        ),
        migrations.AddField(
            model_name='players',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='defaultgame.Games'),
        ),
    ]
