# Generated by Django 2.2.2 on 2019-06-24 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultgame', '0006_auto_20190623_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turns',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
