# Generated by Django 2.2.2 on 2019-06-26 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round', to='war.Games'),
        ),
        migrations.AlterField(
            model_name='turns',
            name='round_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='war.Rounds'),
        ),
    ]
