# Generated by Django 2.2.2 on 2019-06-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war', '0003_players_deck_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='status',
            field=models.CharField(default='new', max_length=200),
        ),
    ]
