# Generated by Django 2.2.2 on 2019-07-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goofspiel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='players',
            name='player',
        ),
        migrations.AlterField(
            model_name='rounds',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.Games'),
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
